app:
  discovery:
    host: localhost
    port: 8761
    user: eureka_admin
    pass: eureka_admin
  keycloak:
    host: localhost
    port: 8090
    realm: microservices

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.keycloak.host}:${app.keycloak.port}/realms/${app.keycloak.realm}

eureka:
  instance:
    hostname: ${app.discovery.host}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${app.discovery.user}:${app.discovery.pass}@${app.discovery.host}:${app.discovery.port}/eureka/

server:
  port: 0

---
spring:
  config:
    activate:
      on-profile: docker

app:
  discovery:
    host: discovery-server
    port: 8761
    user: ${EUREKA_USER}
    pass: ${EUREKA_PASS}
  keycloak:
    host: keycloak
    port: 8080
    realm: microservices
eureka:
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: docker-tmp

app:
  discovery:
    host: host.docker.internal
    port: 8761
    user: ${EUREKA_USER}
    pass: ${EUREKA_PASS}
  keycloak:
    host: keycloak
    port: 8090
    realm: microservices
