app:
  eureka:
    host: localhost
    port: 8761
    user: eureka_admin
    pass: eureka_admin
  keycloak:
    host: localhost
    port: 8090
    realm: microservices

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.keycloak.host}:${app.keycloak.port}/realms/${app.keycloak.realm}

eureka:
  instance:
    hostname: ${app.eureka.host}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${app.eureka.user}:${app.eureka.pass}@${app.eureka.host}:${app.eureka.port}/eureka/

server:
  port: 0

---
spring:
  config:
    activate:
      on-profile: docker

app:
  eureka:
    host: eureka
    port: 8761
    user: ${EUREKA_USER}
    pass: ${EUREKA_PASS}
  keycloak:
    host: keycloak
    port: 8090
    realm: microservices
