spring:
  data:
    mongodb:
      database: product-service
      port: '27017'
      host: localhost

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo
