version: '3.7'

services:
  ms-postgres:
    build: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      KEYCLOAK_DB_NAME: keycloak
      KEYCLOAK_DB_USER: keycloak
      KEYCLOAK_DB_PASSWORD: keycloak
      PGTZ: Europe/Amsterdam
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.0
    restart: on-failure
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://ms-postgres:5432/keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8090
    ports:
      - 8090:8090
    volumes:
      - ./realm/microservices-realm.json:/opt/keycloak/data/import/microservices-realm.json
    command: [ "start-dev", "--import-realm" ]
    depends_on:
      - ms-postgres
