version: '3.7'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.0
    restart: on-failure
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    expose:
      - 8090
    ports:
      - 8090:8090
    volumes:
      - ./realm/microservices-realm.json:/opt/keycloak/data/import/microservices-realm.json
    command: [ "start-dev", "--import-realm" ]

  config-service:
    container_name: config-service
    image: lapotkod/config-service:0.0.1
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker,native
      CONFIG_USER: ${CONFIG_USER}
      CONFIG_PASS: ${CONFIG_PASS}
      EUREKA_USER: ${EUREKA_USER}
      EUREKA_PASS: ${EUREKA_PASS}
    ports:
      - 8888:8888

  discovery-server:
    container_name: discovery-server
    image: lapotkod/discovery-server:0.0.1
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_USER: ${CONFIG_USER}
      CONFIG_PASS: ${CONFIG_PASS}
      EUREKA_USER: ${EUREKA_USER}
      EUREKA_PASS: ${EUREKA_PASS}
    ports:
      - 8761:8761
    depends_on:
      - config-service

  api-gateway:
    container_name: api-gateway
    image: lapotkod/api-gateway:0.0.1
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_USER: ${CONFIG_USER}
      CONFIG_PASS: ${CONFIG_PASS}
      EUREKA_USER: ${EUREKA_USER}
      EUREKA_PASS: ${EUREKA_PASS}
    ports:
      - 8080:8080
    depends_on:
      - config-service
      - discovery-server
      - keycloak
