app:
  config:
    user: cfg_admin
    pass: cfg_admin
  eureka:
    host: localhost
    port: 8761
    user: eureka_admin
    pass: eureka_admin

server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  security:
    user:
      name: ${app.config.user}
      password: ${app.config.pass}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.user}:${app.eureka.pass}@${app.eureka.host}:${app.eureka.port}/eureka/
